// 7-carnival-search/src/App.vue
<script lang="ts">
import { defineComponent } from 'vue'
import Header from './components/Header.vue'
import Card from './components/Card.vue'
import { blocks } from './mockData'

export default defineComponent({
  name: 'App',
  data() {
    return {
      blocks,
    }
  },
  components: { Header, Card },
})
</script>

<template>
  <Header />
  <main>
    <div class="main-content">
      <div class="heading-container">
        <h1>Blocos recomendados</h1>
        <div class="filter-container">
          <span class="active">Lista</span>
          <span class="disabled">Mapa</span>
        </div>
      </div>
      <div class="cards-wrapper">
        <div v-for="block in blocks" :key="block.title">
          <Card v-bind="{ ...block }" />
        </div>
      </div>
    </div>
  </main>
</template>

<style scoped>
main {
  width: 100vw;
  margin-top: 100px;
  color: #121214;
}
.main-content {
  max-width: 80rem;
  margin-inline: auto;
}
.heading-container {
  display: flex;
  margin-bottom: 40px;
  align-items: center;
  justify-content: space-between;
}
h1 {
  font-weight: 700;
  font-size: 32px;
  line-height: 140%;
}
.filter-container {
  border: 1px solid #eaeaea;
  display: flex;
  align-items: center;
  border-radius: 6px;
  padding: 8px;
  height: fit-content;
}
.active {
  padding: 4px 24px;
  display: block;
  background: #6246ea;
  border-radius: 5px;
  font-weight: 700;
  font-size: 14px;
  line-height: 24px;
  text-transform: uppercase;
  color: #ffffff;
  cursor: pointer;
}
.disabled {
  padding: 4px 24px;
  display: block;
  background: transparent;
  border-radius: 5px;
  font-weight: 700;
  font-size: 14px;
  line-height: 24px;
  text-transform: uppercase;
  color: #6246ea;
  cursor: pointer;
}
.cards-wrapper {
  display: grid;
  grid-template-columns: 1fr 1fr 1fr;
  gap: 32px;
  margin-bottom: 150px;
}
</style>

// 2-product-card/src/App.tsx
import styled from 'styled-components'
import { Showcase } from './components/Showcase'
import { Info } from './components/Info'
import { useEffect, useState } from 'react'

export function App() {
  const [products, setProducts] = useState<Product[]>()
  const [activeProduct, setActiveProduct] = useState<number>(0)
  const [interactive360Mode, setInteractive360Mode] = useState<boolean>(false)
  const [bgColor, setBgColor] = useState<string>('#c2aef3')

  useEffect(() => {
    ;(async () => {
      await fetch('./fakeApiProducts/products.json')
        .then((res) => res.json())
        .then((data) => setProducts(data))
    })()
  }, [])

  if (!products) {
    return <>Loading...</>
  }

  const dotProps = (index: number, color: string, activeItem: boolean) => {
    return {
      onClick: () => {
        setActiveProduct(index)
        setInteractive360Mode(false)
        setBgColor(color)
      },
      style: activeItem
        ? { backgroundColor: '#FFFFFF' }
        : { backgroundColor: '#00000050' },
    }
  }

  const mainProps = {
    showCase: {
      pathScene: products[activeProduct].pathScene,
      interactive360Mode: interactive360Mode,
      setInteractive360Mode: setInteractive360Mode,
    },
    info: {
      product: products[activeProduct],
    },
  }

  return (
    <Wrapper bgColor={bgColor}>
      <Main>
        <Showcase {...mainProps.showCase} />
        <Info {...mainProps.info} />
        <Dots>
          {products.map((_, index) => {
            const color = ['#c2aef3', '#c8b49e']
            return (
              <div
                {...dotProps(index, color[index], activeProduct === index)}
                key={index}
              />
            )
          })}
        </Dots>
      </Main>
    </Wrapper>
  )
}

interface StyledProps {
  bgColor: string
}

const Wrapper = styled.div<StyledProps>`
  display: flex;
  padding: 0px;
  text-align: start;
  max-width: 100vw;
  height: 100vh;
  padding: 8px;
  background-color: ${(props) => props.bgColor};
  justify-items: center;
  justify-content: center;
`
const Main = styled.main`
  display: grid;
  margin-block: auto;
  max-height: fit-content;
  width: 100vw;
  column-gap: 30px;
  position: relative;
  grid-template-columns: repeat(2, minmax(0, 1fr));
  section {
    grid-column: span 1 / span 1;
  }
`
const Dots = styled.div`
  left: 50%;
  position: absolute;
  bottom: 180px;
  transform: translateX(-50%);
  display: flex;
  column-gap: 10px;
  div {
    border-radius: 9999px;
    width: 20px;
    height: 20px;
    cursor: pointer;
  }
`
